### PR TITLE
change the names

### PR DESCRIPTION
**Pull request by andres53016**
Hi @CarlPoirier 
I change the names, or in this library I put the 144 footprints?

### CODE REVIEW

**Comment by CarlPoirier** [comment]
You can use P for pitch instead of RM as well.

Didn't you end up having these few footprints to for all of them?

**Comment by michal777** [comment]
In one of my comments I suggested that if new library will be created then much footprints won't introduce a mess and it's no problem to make more.

It's hard to say what people really need. I think that too much is better that not enough (until they meet rules and exists in real world).

**Comment by CarlPoirier** [comment]
Indeed!

It's great, thanks for your contribution!!

**Comment by andres53016** [comment]
You welcome!!

**Pull request merged**
